thuliteio/doks

- assets/js/bootstrap.js
- assets/scss/common/_global.scss
- assets/scss/common/_variables.scss
- assets/scss/components/_code.scss
- assets/scss/components/_comments.scss
- assets/scss/components/_forms.scss
- assets/scss/layouts/_header.scss
- config/_default/menus.toml
- config/_default/params.toml
- layouts/partials/footer/footer.html
- layouts/partials/footer/script-footer.html
- layouts/partials/header/header.html
- layouts/partials/main/docs-navigation.html
- package-lock.json
- package.json
Includes option to load Bootstrap Javascript — set in `./config/_default/params.toml`
```toml
[options]
bootStrapJs = false
```
https://doks-bs5--doks.netlify.app/
> Update bootstrap to 5.0.0-beta2

- assets/scss/app.scss
- assets/scss/common/_dark.scss
- assets/scss/components/_tables.scss
- config/_default/config.toml
- config/postcss.config.js
Example:
```md
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
{.table-striped}
```
Light mode:
Dark mode:
> Add table support in markdown

- assets/scss/layouts/_pages.scss
- config/_default/params.toml
- layouts/docs/single.html
- layouts/partials/main/breadcrumb.html
Set in `./config/_default/params.toml`:
```toml
[options]
breadCrumb = true
```
Example:
Markup:
```html
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="//localhost:1313/">Home</a></li>
<li class="breadcrumb-item"><a href="//localhost:1313/docs/">Docs</a></li>
<li class="breadcrumb-item"><a href="//localhost:1313/docs/prologue/">Prologue</a></li>
<li class="breadcrumb-item active" aria-current="page">Introduction</li>
</ol>
</nav>
```
Note: this is an optional user breadcrumb trail — next to the already implemented JSON-LD for [rich results](https://developers.google.com/search/docs/data-types/breadcrumb):
```json
{
"@context":"http://schema.org",
"@type":"BreadcrumbList",
"itemListElement":[
{
"@type":"ListItem",
"position":1,
"name":"Home", …
```
> Add optional breadcrumb trail

- assets/js/highlight.js
Replace deprecated API with new API.
For further information, please refer to [h-enk/doks - Issue #239](https://github.com/h-enk/doks/issues/239)
> Replace highlightBlock with highlightElement

- layouts/shortcodes/img.html
- package-lock.json
First of all, I just want to say thanks for the awesome theme.
I noticed an issue where images in page bundles fail to load if the site is not deployed to the root. For example, if you deploy the site to _www.example.com/projects/info_.
To reproduce the issue, in the `say-hello-to-doks` blog post embed the `say-hello-to-doks.png` and run a build. 
Checking out the resulting `index.html`, the first entry in `data-srcset` has an absolute URL but the rest are relative URL's. The relative links will fail to load once deployed since the default config is using canonical URL's with a baseURL.
This seems because `RelPermalink` is used in the `img` shortcode. Switch to `Permalink` and rebuild to fix the issue.
> Fix issue where page bundle images fail to load

- layouts/shortcodes/alert.html
- Adds `.Inner` block for large text content
You can use this shortcode in several ways:
1. with named parameter
```
{{< alert icon="👉" text="foobar" />}}
```
2. with inline form
```
{{< alert icon="👉" >}}
fghfghfghghfg
{{< /alert >}}
```
> **🔥  Important** 
> - if you use the inline form with the `text` parameter, the parameter is dominant and will be used.
> - Always use the terminating `/` in shortcodes. Otherwise hugo will populate empty `.Inner` params which truncates the page in this case
> - See https://gohugo.io/templates/shortcode-templates/#inline-shortcodes
> ✨ Uses inline shortcode in alerts for large texts

- assets/scss/common/_dark.scss
- assets/scss/components/_code.scss
- Increases contrast for horizontal scrollbar in `pre code` blocks
- adds matching scss definition for code blocks in dark mode
> I'm not sure if i found all relevant css definitions, or used the preexisting scss variables / color definition
- should fix #222
> 🐛 Fixes scrollbar in code blocks

- package.json
markdownlint command was not doing anything on Linux. It worked fine in Windows. This fix addresses and now it is working on both operating systems. Please refer to https://github.com/igorshubovych/markdownlint-cli#globbing-examples and notice that the command requires quotes on Linux.
> Fix lint tests on Linux.

- assets/js/index.js
- config/_default/config.toml
- config/_default/menus/menus.en.toml
- config/_default/params.toml
- content/en/versions.md
- data/docs-versions.yml
- layouts/_default/versions.html
- layouts/index.headers
- layouts/index.html
- layouts/index.redirects
- layouts/partials/footer/script-footer.html
- layouts/partials/head/stylesheet.html
- layouts/partials/header/header.html
1. In `./config/_default/params.toml` under `[options]`:
- set `docsVersioning = true`
- add `docsVersion = 1.0`
2. In `./config/production/config.toml`, set `canonifyURLs = false`
3. In `./config/_default_/config.toml` under `[permalinks]`, set `docs = "/docs/1.0/:sections[1:]/:title/"`
4. In `./layouts/index.redirects` add:
```bash
/docs/1.0/prologue/   /docs/1.0/prologue/introduction/
/docs/1.0/help/       /docs/1.0/help/how-to-update/
/docs/1.0/            /docs/1.0/prologue/introduction/
/docs/                /docs/1.0/prologue/introduction/
/docs/0.1/*           https://v0-1-0--doks-versioning-poc.netlify.app/docs/0.1/:splat  200
/docs/0.2/*           https://v0-2-0--doks-versioning-poc.netlify.app/docs/0.2/:splat  200
```
5. Update `./config/_default/menus.en.toml`, section …
> feat: add versioning setup

- assets/scss/common/_fonts.scss
I've tested this by changing the _rendered CSS_ as below on Safari, Firefox and Chrome on macOS 11.6.2. I haven't actually run Hugo with the below change, because I don't have a doks install set up to develop with. But I hope it's simple enough to verify that this change does what's expected.
Here's [the relevant MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src). MDN is actually kind of confusing here. The formal syntax says that you should use a font family name inside `local()`, but the code in two other places say you should actually use the font face name. And the [example](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src#examples) is quite explicit that the PostScript name is an acceptable value here.
It looks like MDN got it wrong, because the …
> [#604] Allow Firefox on macOS to see italic text.

- assets/scss/common/_dark.scss
- assets/scss/components/_buttons.scss
- config/_default/menus/menus.en.toml
- layouts/partials/header/header.html
Supports one level deep.
Set in `./config/_default/menus/menus.en.toml`:
```toml
[[main]]
name = "Prologue"
weight = 30
identifier = "prologue"
url = "/docs/prologue/"
[[main]]
name = "Introduction"
weight = 35
identifier = "introduction"
url = "/docs/prologue/introduction/"
parent = "prologue"
[[main]]
name = "Quick Start"
weight = 40
identifier = "quick-start"
url = "/docs/prologue/quick-start/"
parent = "prologue"
[[main]]
name = "Commands"
weight = 45
identifier = "commands"
url = "/docs/prologue/commands/"
parent = "prologue"
```
https://deploy-preview-642--doks.netlify.app/
> Adds support for sub navigation main menu

- config/_default/params.toml
- layouts/partials/main/edit-page.html
Can be used if the folder with your content is in a subfolder so if your project wishes to contain code and docs in the same repo it's convenient to do so. Additionally includes some refactoring in the edit-page.html logic to make it  easier to manage. Also added Bitbucket and BitbucketServer repo types.
> feat: edit link docs repo subpath

- layouts/partials/sidebar/auto-default-menu.html
- layouts/partials/sidebar/manual-collapsible-menu.html
- layouts/partials/sidebar/manual-default-menu.html
Removes usage of deprecated .URL parameter, and brings the menus usage of .Permakink for href's to be consistent.
I don't think a screenshot is relevant. But I modeled these changes after the usage of .Permalink here: https://github.com/h-enk/doks/blob/master/layouts/partials/sidebar/auto-collapsible-menu.html#L41
Removes a deprecated usage of a parameter, suppresses an error, and makes the menu's slightly more consistent.
> fix(layouts): use the permalink instead of url

- assets/js/index.js
This makes the search bar continue to work when many (2000+) pages are added.
This adjusts the way in which the search index is built so that the call stack is not exceeded on some browsers (see #738 for browser compatibility). I'm not familiar with Hugo templating so if there's a preferred way, we can go that route!
Previously, the compiled template would add to the array `index` by chaining `.add()` calls.
```js
index.add(
{
id: 3,
href: "/docs/prologue/doc1/",
title: "doc1",
description: "Doks comes with commands for common tasks.",
content: ""
})
.add(
{
id: 4,
href: "/docs/prologue/doc10/",
title: "doc10",
description: "Doks comes with commands for common tasks.",
content: ""
})
.add(
{
id: 5,
href: "/docs/prologue/doc100/",
title: "doc100",
description: "Doks comes with commands for …
```
> fix(flexsearch): separate chain of calls into statements

- layouts/index.redirects
This fixes an issue where the generation of aliases may remove newlines erroneously moving subsequent lines to the same line as the last alias or otherwise mangle the output.
Can be  tested in a short-code with the following content rendered in a fence (you can also see the output of the original using this method just with the original template; you can also replace `.Aliases` with `dict` to see what it does with an empty enumerable I believe):
```html
start
{{- range $p := .Site.Pages }}
{{- range .Aliases }}
{{ . }} {{ $p.RelPermalink }}
{{- end }}
{{- end }}
end
```
This prevents an error in netlify about a redirect which is improperly formatted.
> fix(layouts): index.redirects truncates newline

- layouts/partials/head/custom-head.html
- layouts/partials/head/head.html
Add empty file named `partials/head/custom-head.html`, which is "partial" called from `partials/head/head.html`
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```
`doks-child-theme` is hard to customize to import some external code like code from CDN.
Even it is not for deep custom, flexible `head` can be allowed, I think.
In addition, some user-adding tags in `<head>` cannot be categorized to existing "partials" in head, such as "favicons.html", "seo.html". So custom-head.html is useful for doks user (i.e. non-doks-child-theme user).
> Add custom-head.html

- assets/scss/common/_global.scss
- assets/scss/components/_buttons.scss
- assets/scss/components/_search.scss
- assets/scss/layouts/_header.scss
- config/_default/params.toml
- config/postcss.config.js
- layouts/docs/single.html
- layouts/partials/footer/script-footer.html
- layouts/partials/header/header.html
- layouts/partials/sidebar/docs-toc.html
- Drop section specific navigation bar — freeing up vertical space
- Show (if options are set) search bar, language switch dropdown, and version switch dropdown on ALL pages  — making navigation more direct
- Make navigation bar sticky (if option is set, default true) on large + mobile screens — making navigation more direct (no need to scroll to top)
- Make "On this page" section collapse on smaller screens  — freeing up vertical space
- Support section navigation for sections defined in `./config/_default/params.toml`:
```toml
[sections]
sectionNav = ["docs", "guides"]
```
https://deploy-preview-782--doks.netlify.app/
- Making navigation easier /more direct
- Back to original design idea
- Preparing for global search
- Preparing for scroll to top button (option)
> Single navbar

- content/en/docs/help/_index.md
- content/en/docs/prologue/_index.md
- layouts/partials/sidebar/auto-collapsible-menu.html
- layouts/partials/sidebar/auto-default-menu.html
This restores the default hugo sorting behaviour.
Fixes #781
This restores the default sorting behavior of sections. It will require that users using the auto menus include a weight in the `_index.md` of each sub-section.
See https://github.com/h-enk/doks/issues/781#issuecomment-1154968981
> fix(menus): sort pages and sections by default order

- package-lock.json
- package.json
This should be understood as communication that I believe the issue is fixed with the changes made by @h-enk and @danielfdickinson. I did not personally fix this I'm just bumping the dep.
This fixes an issue where if a figure image has a link the hugo build fails.
Fixes #820
Brief explanation of the proposed changes.
Include a basic example, screenshots, or links.
Why are we doing this? What use cases does it support? What is the expected outcome?
> fix: build fails when figure has link

- package-lock.json
- package.json
Update hugo to the latest version, there are various performance improvements and bug fixes.
Hugo has changed how they name the packages so hugo-install needs to support that.
N/A
Improvements in hugo
- [N/A] Supports all screen sizes (if relevant)
- [N/A] Supports both light and dark mode (if relevant)
> Update hugo to 0.107.0 and hugo-install to >=4.0.1

- layouts/partials/header/header.html
Currently, the navbar-brand links to "/".
Given that BaseURL is configurabe, I think this is probably a bug.
before:
```html
<a class="navbar-brand order-0" href="/" aria-label="Foo">Foo</a>
```
after:
```html
<a class="navbar-brand order-0" href="/foo" aria-label="Foo">Foo</a>
```
In some instances, a URL like `/` is not possible. This is the case for example for websites like GitLab pages which serve under `user.pages.instance.tld/projectname`
For some reason my IDE is not allowing me to edit commit messages, but this is probably not that big of an issue for this PR, as you can just edit the commit message via squashing this PR into main 😉
> fix: navbar-brand href now links to the BaseURL instead of `/`

- .changeset/large-peas-share.md
- config/_default/params.toml
See https://github.com/gethyas/doks-core/pull/102. Body copied below.
Allow users to provide a custom Kroki URL instead of hard-coding
https://kroki.io.
In `params.toml`, users of this theme can set a custom Kroki URL, such
as a local instance:
```toml
[doks]
krokiURL = "http://localhost:8000"
```
I tried my best to keep proper backwards compatibility should users not
provide this configuration key *at all*—see the diff. Should this not be
acceptable, please let me know.
At times, the upstream kroki.io service may run into resource exhaustion.
This can be due to a high volume of requests or a temporary outage.
During an automated build, this isn't so bad—caches should exist and
therefore not hit Kroki as often.
However, especially during the writing phase of
documentation, where fast …
> feat: allow custom kroki host

- .changeset/config.json
- .changeset/perfect-emus-fly.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
- README.md
- assets/jsconfig.json
- config/_default/hugo.toml
- config/_default/languages.toml
- config/_default/menus/menus.en.toml
- config/_default/module.toml
- config/_default/params.toml
- config/postcss.config.js
- layouts/index.html
- package-lock.json
- package.json
- theme.toml
Brief explanation of the proposed changes.
Include a basic example, screenshots, or links.
Why are we doing this? What use cases does it support? What is the expected outcome?
> Update for migration from Hyas to Thulite

- .changeset/cool-badgers-leave.md
- .changeset/grumpy-ducks-divide.md
- config/_default/hugo.toml
- config/_default/module.toml
- netlify.toml
- package-lock.json
- package.json
In Hugo 0.146.0, the layout application priority has changed. ( See [Reimplement and simplify Hugo's template system #13541](https://github.com/gohugoio/hugo/pull/13541) )
This patch fixes an issue where the Doks theme is not rendered correctly with Hugo version 0.146.0 and above due to this change.
By applying this patch, the Doks theme will render properly on Hugo versions 0.146.0 and above.
However, please note that the theme will not render correctly on versions lower than 0.146.0 after applying this PR. Therefore, it is recommended to update Hugo to the latest version.
While it is technically possible to modify doks-core / @thuliteio/core to maintain compatibility with older versions, such changes would likely introduce significant side effects.
Additionally, since doks-core v1.8.1 …
> fix : Fixes the issue of layout breaking due to changes in layout priority in Hugo 0.146.0
